#input and output file names
input file location: histos_4l_ttZ_studies_4t_lepCut
input file label: ttV_lepCuts_v1
output file location: pdf_4l_ttZ_studies_4t_lepCut_blind

#drawing options
skip systematics: true
draw ratio plot: true
draw legend: true
log scale: false
save png: true
save pdf: true
blinded: true
KS test: false
selection info : false
SF info: false

#luminosity and era
luminosity: 19.5
luminosity error: 0.044
trigger SF error: 0.02
lumi era string: "                #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}"

#Lepton categories: "draw name"
lepton categories:
    mu_mu:
        data samples: [inclusive_data]
        excluded samples: []
        tex name: " #mu #mu "
    ele_ele:
        data samples: [inclusive_data]
        excluded samples: []
        tex name: " e e "
    4l:
        data samples: [inclusive_data]
        excluded samples: []
        tex name: " 4 lepton "

#Jet-tag categories: "draw name"
jet tag categories:
# #     ## ZZ
# #     ge0j: " + #geq0 jets"
# #     ge2j: " + #geq2 jets"
# #     ge0j_Zpeak: " + #geq0 jets, Z-peak"
#     ge2j_Zpeak: " + #geq2 jets, Z-peak"
# #     ge0j_Zmask: " + #geq0 jets, Z-mask"
# #     ge2j_Zmask: " + #geq2 jets, Z-mask"
# # #     ge0j_metLD: " + #geq0 jets + MetLD"
# # #     ge2j_metLD: " + #geq2 jets + MetLD"
# # #     ge0j_1bloose: " + #geq0 jets + tag"
# # #     ge2j_1bloose: " + #geq2 jets + tag"
# # #     ge0j_metLD_1bloose: " + #geq0 jets + tag"
# # #     ge2j_metLD_1bloose: " + #geq2 jets + tag"
# #     ge0j_Zpeak_metLD_1bloose: " + #geq0 jets + tag"
    #ge2j_Zpeak_1bloose: " + #geq2 jets + tag"
    ge2j_Zpeak_lowMet_lf: " + #geq2 jets + lowMet + lf"
    ge2j_Zpeak_metLD_1bloose: " + #geq2 jets + MetLD + tag"
    #ge2j_Zmask_1bloose: " + #geq0 jets + tag"
    ge2j_Zmask_lowMet_lf: " + #geq2 jets + lowMet + lf"
    ge2j_Zmask_metLD_1bloose: " + #geq2 jets + MetLD + tag"

#     2lep_pt: " + 2 leps pT cut"
#     3lep_pt: " + 3 leps pT cut"
#     4lep_pt: " + 4 leps pT cut"

#     2lep_pt_Zpeak1_Zpeak2: " + 2 leps pT cut + 2 Z"
#     3lep_pt_Zpeak1_Zpeak2: " + 3 leps pT cut + 2 Z"
#     4lep_pt_Zpeak1_Zpeak2: " + 4 leps pT cut + 2 Z"

#     2lep_pt_Zpeak1_Zmask2: " + 2 leps pT cut + 1 Z"
#     3lep_pt_Zpeak1_Zmask2: " + 3 leps pT cut + 1 Z"
#     4lep_pt_Zpeak1_Zmask2: " + 4 leps pT cut + 1 Z"

#     2lep_pt_Zmask1: " + 2 leps pT cut + 0 Z"
#     3lep_pt_Zmask1: " + 3 leps pT cut + 0 Z"
#     4lep_pt_Zmask1: " + 4 leps pT cut + 0 Z"

#     eq0j_2lep_pt: " + #eq0 jets + 2 leps pT cut"
#     eq0j_3lep_pt: " + #eq0 jets + 3 leps pT cut"
#     eq0j_4lep_pt: " + #eq0 jets + 4 leps pT cut"

#     eq0j_2lep_pt_Zpeak1_Zpeak2: " + #eq0 jets + 2 leps pT cut + 2 Z"
#     eq0j_3lep_pt_Zpeak1_Zpeak2: " + #eq0 jets + 3 leps pT cut + 2 Z"
#     eq0j_4lep_pt_Zpeak1_Zpeak2: " + #eq0 jets + 4 leps pT cut + 2 Z"

#     eq0j_2lep_pt_Zpeak1_Zmask2: " + #eq0 jets + 2 leps pT cut + 1 Z"
#     eq0j_3lep_pt_Zpeak1_Zmask2: " + #eq0 jets + 3 leps pT cut + 1 Z"
#     eq0j_4lep_pt_Zpeak1_Zmask2: " + #eq0 jets + 4 leps pT cut + 1 Z"

#     eq0j_2lep_pt_Zmask1: " + #eq0 jets + 2 leps pT cut + 0 Z"
#     eq0j_3lep_pt_Zmask1: " + #eq0 jets + 3 leps pT cut + 0 Z"
#     eq0j_4lep_pt_Zmask1: " + #eq0 jets + 4 leps pT cut + 0 Z"

#Systematics used in error bars
systematics:
    - nominal
    - weight_PUUp
    - weight_PUDown
    - topPtWgtDown
    - topPtWgtUp
    - csvWeightHFUp
    - csvWeightHFDown
    - csvWeightLFUp
    - csvWeightLFDown
    
# Samples drawn on top, scaling (1.0, 2.0, "norm" for area-normalized) 

signal samples:
    ttbarZ:
        draw name: "t#bar{t}Z"
        color: kSpring+2
        samples: [ttbarZ]
        stack or line: stack
        line width: 2 # must be integer
        scale: 1.0

#Samples in each group will be added together and appear as a single entry in the stack plot
background samples:
    inclusive_data_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [inclusive_data_NP_sideband]

    DoubleMu_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleMu_NP_sideband]

    DoubleElectron_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleElectron_NP_sideband]

    #ttbar:
        #draw name: ttbar
        #color: kRed
        #systematics: all
        #samples:
            #- ttbar_lj
            #- ttbar_ll

#     zz_lowmll:
#         draw name: "ZZ low mass"
#         color: kMagenta
#         samples: [zz_lowmll]
        
#     zz_llll:
#         draw name: "ZZ"
#         color: kAzure-9
#         samples: [zz_llll]
        
    zz_lf_llll:
        draw name: "ZZ_lf"
        color: kAzure-9
        samples: [zz_lf_llll]
        
    zz_cc_llll:
        draw name: "ZZ_cc"
        color: kAzure-8
        samples: [zz_cc_llll]
        
    zz_b_llll:
        draw name: "ZZ_b"
        color: kAzure-7
        samples: [zz_b_llll]
        
    zz_bb_llll:
        draw name: "ZZ_bb"
        color: kAzure-6
        samples: [zz_bb_llll]
        
    Others:
        draw name: "Rare SM"
        color: kSpring+8
        samples: [tbZ_ll, WpWpqq, WWDPI] #WmWmqq


    triboson:
        draw name: "triboson"
        color: kViolet
        samples: [www, wwz]

    ttbarGStar:
        draw name: "t#bar{t}G*"
        color: kCyan-3
        samples: [ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt]
                                        
    ttbarW:
        draw name: "t#bar{t}W"
        color: kGreen-5
        samples: [ttbarW]
                                        
    ttbarWW:
        draw name: "t#bar{t}WW"
        color: kBlue-9
        samples: [ttbarWW]
                                        
    ttH125:
        draw name: "t#bar{t}H125"
        color: kRed
        samples: [ttH125]
                                        
    #Zjets:
        #draw name: Zjets
        #color: kBlue
        #systematics: all
        #samples:
            #- zjets_0p
            #- zjets_1p
            #- zjets_2p
            #- zjets_3p
            #- zjets_4p

#distribution: [title, underflow, overflow]
distributions:
    numAllMuons: ['number of muons', true, true]
    numAllNonZMuons: ['number of non-Z muons', true, true]
    numJets: ['number of jets', true, true]
    numLooseBJets: ['number of loose b-tagged jets', true, true]
    numMediumBJets: ['number of medium b-tagged jets', true, true]
    numTightBJets: ['number of tight b-tagged jets', true, true]
    all_nonZ_leptons_by_pt_1_pt: ['First non-Z lepton pT', true, true]
    #all_nonZ_leptons_by_pt_1_pt_med: ['First non-Z lepton pT', true, true]
    #all_nonZ_leptons_by_pt_1_pt_low: ['First non-Z lepton pT', true, true]
    all_nonZ_leptons_by_pt_2_pt: ['Second non-Z lepton pT', true, true]
    #all_nonZ_leptons_by_pt_2_pt_med: ['Second non-Z lepton pT', true, true]
    #all_nonZ_leptons_by_pt_2_pt_low: ['Second non-Z lepton pT', true, true]
##     all_nonZ_leptons_by_pt_1_eta: ['Non-Z lepton eta', true, true]
##     all_nonZ_leptons_by_pt_1_jetBTagCSV: ['Non-Z lepton jetBTagCSV', true, true]
    ZLike_pt_leplep_SFOS_all: ['Z pT', true, true]
    #ZLike_pt_leplep_SFOS_all_low: ['Z pT', true, true]
    met_ld: ['MetLD', true, true]
    #met_ld_low: ['MetLD', true, true]
    #WLike_MT_met_lep: ['MT(met, lep)', true, true]
    #WLike_MT_met_lep_low: ['MT(met, lep)', true, true]
#    ## ttZ
    all_Z_leptons_by_pt_1_pt: ['First Z lepton pT', true, true]
    #all_Z_leptons_by_pt_1_pt_med: ['First Z lepton pT', true, true]
    #all_Z_leptons_by_pt_1_pt_low: ['First Z lepton pT', true, true]
    all_Z_leptons_by_pt_2_pt: ['Second Z lepton pT', true, true]
    #all_Z_leptons_by_pt_2_pt_med: ['Second Z lepton pT', true, true]
    #all_Z_leptons_by_pt_2_pt_low: ['Second Z lepton pT', true, true]
    min_nonZ_lepton_eta: ['Min non-Z lepton eta', true, true]
    max_nonZ_lepton_eta: ['Max non-Z lepton eta', true, true]
    jets_by_pt_1_pt: ['First jet pT', false, true]
    jets_by_pt_2_pt: ['Second jet pT', false, true]
#     min_mass_leplep_all: ['min dilepton mass', true, true]
    ZLike_mass_leplep_SFOS_all: ['Z mass', true, true]
    #ZLike_mass_leplep_SFOS_all_med: ['Z mass med', true, true]
    #ZLike_mass_leplep_SFOS_all_low: ['Z mass low', true, true]
    ZLike_eta_leplep_SFOS_all: ['Z eta', true, true]
    ZLike_mass_leplep_SFOS_all_2: ['Second Z mass', false, true]
    #ZLike_mass_leplep_SFOS_all_2_med: ['Second Z mass med', false, true]
    #ZLike_mass_leplep_SFOS_all_2_low: ['Second Z mass low', false, false]
    met_pt: ['MET', true, true]
    #met_pt_low: ['MET', true, true]
    mht: ['MHT', true, true]
    #mht_low: ['MHT', true, true]
    sum_pt: ['Sum pT', false, true]
    sum_jet_pt: ['Sum jet pT', false, true]
    mass_of_jets: ['Mass of all jets', false, true]
# #     WLike_dijet_mass_X1b: ['W mass (exclude one b-jet)', true, true]
# #     WLike_dijet_mass_X2b: ['W mass (exclude two b-jets)', true, true]
#     topLike_MT_met_lep_b_175: ['top MT(met, lep, b)', false, true]
#     topLike_mass_lep_b_100: ['top mass(lep, b)', false, true]
# #     topLike_multijet_mass_b1: ['top mass(jets, b1)', true, true]
# #     topLike_multijet_mass_b2: ['top mass(jets, b2)', true, true]
# #     topPairLike_MT_met_lep_jets: ['top pair MT(met, lep, jets)', true, true]
# #     topPairLike_mass_lep_jets: ['top pair mass(lep, jets)', true, true]
                                                                