#input and output file names
input file location: histos_3l_ttW_studies_3t_lepCut
input file label: ttV_lepCuts_v1
output file location: pdf_3l_ttW_studies_3t_lepCut_blind

#drawing options
skip systematics: true
draw ratio plot: true
draw legend: true
log scale: false
save png: true
save pdf: true
blinded: true
KS test: false
selection info : false
SF info: false

#luminosity and era
luminosity: 19.5
luminosity error: 0.044
trigger SF error: 0.02
lumi era string: "                #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}"

#Lepton categories: "draw name"
lepton categories:
    mu_mu:
        data samples: [DoubleMu]
        excluded samples: []
        tex name: " #mu #mu "
    ele_ele:
        data samples: [DoubleElectron]
        excluded samples: []
        tex name: " e e "
    3l:
        data samples: [inclusive_data]
        excluded samples: []
        tex name: " 3 lepton "

#Jet-tag categories: "draw name"
jet tag categories:
#     ge0j: " + #geq0 jets"
#     ge1j: " + #geq1 jet"
#     ge2j: " + #geq2 jets"
#     ge0j_metLD: " + #geq0 jets + met_ld"
#     ge1j_metLD: " + #geq1 jet + met_ld"
#     ge2j_metLD: " + #geq2 jets + met_ld"
    eq1j_lf: " + #eq1 jet + lf"
    ge2j_lf: " + #geq2 jets + lf"
    eq1j_bloose: " + #eq1 jet + tags"
    ge2j_bloose: " + #geq2 jets + tags"

#     eq1j_bloose: " + #eq1 jet + tags"
#     eq2j_bloose: " + #eq2 jets + tags"
#     ge3j_bloose: " + #geq3 jets + tags"

#     ttbar: "ttbar"

#Systematics used in error bars
systematics:
    - nominal
    - weight_PUUp
    - weight_PUDown
    - topPtWgtDown
    - topPtWgtUp
    - csvWeightHFUp
    - csvWeightHFDown
    - csvWeightLFUp
    - csvWeightLFDown
    
# Samples drawn on top, scaling (1.0, 2.0, "norm" for area-normalized) 

signal samples:
    ttbarW:
    #ttW:
        draw name: "t#bar{t}W"
        color: kGreen-5
        #color: kBlue
        samples: [ttbarW]
        stack or line: stack
        line width: 2 # must be integer
        scale: 1.0

#Samples in each group will be added together and appear as a single entry in the stack plot
background samples:
    inclusive_data_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [inclusive_data_NP_sideband]

    DoubleMu_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleMu_NP_sideband]

    DoubleElectron_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: [40PercentRateUp, 40PercentRateDown]
        samples: [DoubleElectron_NP_sideband]

    #ttbar:
        #draw name: ttbar
        #color: kRed
        #systematics: all
        #samples:
            #- ttbar_lj
            #- ttbar_ll

    wz_lll:
        draw name: "WZ"
        color: kViolet-4
        samples: [wz_lf_lll, wz_cc_lll, wz_b_lll, wz_bb_lll]
        
    zz_llll:
        draw name: "ZZ"
        color: kAzure-9
        samples: [zz_lf_llll, zz_cc_llll, zz_b_llll, zz_bb_llll]
        
    Others:
        draw name: "Rare SM"
        color: kSpring+8
        samples: [tbZ_ll, WpWpqq, WWDPI] #WmWmqq


    triboson:
        draw name: "triboson"
        color: kViolet
        samples: [www, wwz]

    ttbarGStar:
        draw name: "t#bar{t}G*"
        color: kCyan-3
        samples: [ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt]
                                        
    ttbarZ:
        draw name: "t#bar{t}Z"
        color: kSpring+2
        samples: [ttbarZ]
                                        
    ttbarWW:
        draw name: "t#bar{t}WW"
        color: kBlue-9
        samples: [ttbarWW]
                                        
    ttH125:
        draw name: "t#bar{t}H125"
        color: kRed
        samples: [ttH125]

#     ttbarW:
#         draw name: "t#bar{t}W"
#         color: kGreen-5
#         samples: [ttbarW]
        
#distribution: [title, underflow, overflow]
distributions:
    numAllMuons: ['number of muons', true, true]
    numJets: ['number of jets', true, true]
    numLooseBJets: ['number of loose b-tagged jets', true, true]
    numMediumBJets: ['number of medium b-tagged jets', true, true]
    numTightBJets: ['number of tight b-tagged jets', true, true]
    all_SS_leptons_by_pt_2_pt: ['Second SS lepton pT', true, true]
    all_SS_leptons_by_pt_2_eta: ['Second SS lepton eta', true, true]
    #all_SS_leptons_by_pt_2_jetBTagCSV: ['Second SS lepton jetBTagCSV', true, true]
    met_ld: ['MetLD', true, true]
    all_SS_leptons_by_pt_1_pt: ['First SS lepton pT', true, true]
    all_OS_leptons_by_pt_1_pt: ['OS lepton pT', true, true]
    jets_by_pt_1_pt: ['First jet pT', false, true]
    jets_by_pt_2_pt: ['Second jet pT', false, true]
    min_mass_leplep_all: ['min dilepton mass', true, true]
    min_mass_leplep_OS: ['min OS dilepton mass', true, true]
    met_pt: ['MET', true, true]
    mht: ['MHT', true, true]
    sum_pt: ['Sum pT', true, true]
    sum_jet_pt: ['Sum jet pT', true, true]
    mass_of_jets: ['Mass of all jets', true, true]
    jets_MT_mass_ratio: ['MT/mass of all jets', true, true]
    everything_MT_mass_ratio: ['MT/mass of everything', true, true]

    Match_ttW_3l_Bb: ['match score Bb', true, true]
    FinalBDT: ['final BDT', false, false]

